name: Demo #Nom workflow
on:
  workflow_dispatch:
  push:
    branches:
      - develop
    #paths-ignore:
    #  - '.github/workflows/*'
  pull_request:
    branches:
      - main
    types:
      - opened

jobs: #Commandes à exécuter
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code
        uses: actions/checkout@v4
      - name: Install java
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: maven
      - name: Build Code
        run: mvn compile
      - name: Run the scan against the codebase #CodeQL scan action
        id: run-scan
        uses: tonys-code-base/run-codeql-analysis-action@master
        with:
          language_to_scan: java
          token: ${{ secrets.GITHUB_TOKEN }}
        shell: chmod +x /home/runner/work/_actions/tonys-code-base/run-codeql-analysis-action/master/src/codeql-scan.sh
      - name: Execute test
        run: mvn test


